name: Steps Exemples
on:
  workflow_dispatch

jobs:
  steps-exemples:
    runs-on: ubuntu-latest
    steps:
     - run: mkdir -p testmachine
     - run: uname -a > testmachine/output.txt
     - run: cat testmachine/output.txt
     - run: ls -alhR
