name: Uses Exemples
on: 
  workflow_dispatch:

jobs:
  uses-exemples;
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository code
        uses: actions/checkout@v5.0.1
      
      - name: Install Python v3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Execute Python script
        run: python my_script.py
